### ISSUE TITLE
Update database schema

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#122]
## User story

1. As a developer
2. I want / need an updated database schema
3. So that it natches the Kubernetes API

## Acceptance criteria

- [x] Kubernetes API and database schema match

## Linked Issues

- **Blocked by:**
- **Related to:** #85 
- **Implements**

## Additional information

- none

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
First changes with watcher implementation, needs further implementation

**Comment by njochens** [comment]
Excel with Kubernetes API representation is uploaded to confluence and can be updated with new approaches for the scheme. For example what fields should be imported and if they should, as a special field in PostgreSQL or as plain JSON?

**Comment by jandegen** [comment]
Scheme specified and documented. Changes will be applied once feature implementationr requires it.
