### ISSUE TITLE
Run all tests in CI

### ISSUE THREAD

**Issue by vringar** [amosproj/amos2023ss04-kubernetes-inventory-taker#160]
**Describe the bug**
Currently the cypress and jest tests aren't run in CI.

**To Reproduce**

Create failing jest test, push the branch and open a PR.
See that the checks are still green

**Expected behavior**

If any of the tests are failing the pipeline shouldn't be green

**Comment by smnws** [comment]
basically done, but I didn't want to merge in the last minute and before the failing listsort_test.cy.js cypress test is fixed

**Comment by vringar** [comment]
Fixed by #182
