### ISSUE TITLE
Container Sorting Functionality Not Working Properly After Implementing Search Feature

### ISSUE THREAD

**Issue by smnws** [amosproj/amos2023ss04-kubernetes-inventory-taker#181]
**Describe the bug**
After the recent implementation of the search feature, the sorting functionality stopped working as expected. It appears that the sorting functions handleSortAsc and handleSortDsc are operating on the sortedList state, while the displayed list is actually based on the filteredContainers state. As a result, sorting is not having any effect on the list displayed to the user. The problem was introduced with [this PR](https://github.com/amosproj/amos2023ss04-kubernetes-inventory-taker/pull/171)

**To Reproduce**

1. Navigate to the Container Table: http://localhost:3000/
2. Click on STATUS -> Assending
3. See that nothing happens

**Expected behavior**
The list should be sorted based on the selected sorting option (ascending or descending)

**Additional Notes**
- It might be better to use buttons or other interactive elements for triggering actions in the dropdown instead of anchor tags
- It should be spelled "Ascending" and not "Assending"

**Comment by muhdfahadali** [comment]
Resolved sorting functionality issue.
Changed anchor tag with buttons

**Comment by jandegen** [comment]
Test cases are failing

**Comment by vringar** [comment]
Test cases fixed in #194
