### ISSUE TITLE
Pre-commit Doesn't Pass All Relevant File Paths To Eslint

### ISSUE THREAD

**Issue by smnws** [amosproj/amos2023ss04-kubernetes-inventory-taker#186]
**Describe the bug**
In our current .pre-commit-config.yaml, the ESLint hook's entry point is defined as:
`entry: bash -c 'cd Explorer && npm run precommit-lint "$@"'`
This does not include the relevant file path passed by pre-commit as $0 since $@ only includes the positional parameters from $1 onwards. As a result, ESLint does not receive the filenames that need to be linted.

**To Reproduce**
The issue was identified by observing that $@ does not include $0, which holds a relevant file path. This was verified by using the following test entry:
```
entry: |
  bash -c 'for i in {0..9}; do echo "arg $i: ${!i}"; done; echo "\$@ args: $@"'
```

1. Change eslint entry in amos2023ss04-kubernetes-inventory-taker/.pre-commit-config.yaml
2. Run `pre-commit run --all --verbose`
3. Notice that "$@ args" doesn't contain $0 and $0 contains a relevant path 

**Expected behavior**
When pre-commit runs ESLint, it should pass all relevant file paths to the ESLint command.

**Comment by vringar** [comment]
Fixed in #187 by passing $0 explicitly
