### ISSUE TITLE
Create coding guidelines

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#27]
## Task
Create and agree on coding guidelines and additional tools (linting, auto-formatting, git pre-commit) which every developers agrees on and uses it.

**Comment by jandegen** [comment]
We suggest a branching strategy like
- feature/#y<issue-number>-title
- bug/#<issue-number>-title

You can directly create a branch from a user story, but be careful, you need to add the #

**Comment by lifesbest23** [comment]
For golang I would suggest using [gofmt](https://pkg.go.dev/cmd/gofmt) either as a pre-commit hook locally or as an GitHub action.
