### ISSUE TITLE
Initialize a base website

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#38]
## User story
1. As a developer
2. I want / need a base website
3. So that I can build the future frontend on that base

## Acceptance criteria
- [x] Website shall be buildable without errors on localhost
- [x] Website shall be running inside a docker container
- [x] Set up a docker-compose file to automate building the docker container
- [x] The website shall be a blank page with a header
- [x] Initialize a central sass (/css/lass) file that will be used for styling the whole website
- [ ] Initialize a "helper" file for all upcoming helper functions
- [ ] Initialize a "const" file for all upcoming constant values

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jandegen** [comment]
Decided against helper and const implementation for now. Will be added if needed
