### ISSUE TITLE
Create list with static data (container names)

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#39]
## User story
1. As a developer
2. I want / need a list on the website
3. So that I have a base list we can later fill with more meaningful data

## Acceptance criteria
- [ ]  The list shall be on the main page of the website
- [ ] The list shall contain one column (name)
- [ ] It shall be filled with static data

## Additional notes
- The static data shall be formatted as a dict
- The list is implemented as reusable, configureable component

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by PhlppKrmr** [comment]
Example for static data:
const data = [
  {name: "Hallo"},
  {name: "Hallo2"}
}

We will most likely keep `name` as an attribute in the database to keep you from having to make major changes later on.

**Comment by jandegen** [comment]
implemted but pull request still open
