### ISSUE TITLE
Fill happiness index

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#4]
## Task
Use the happiness index tool at https://happy-amos.appspot.com/  to submit how you feel about the project.

This is done once at the end of a sprint, during the team meeting retrospective. 
Entering your happiness is different from sending stand-up emails; this should not be mixed.
If there are problems with using the service, please switch off ad blockers and the like.

**Comment by jandegen** [comment]
Some people hare having access issues

**Comment by PhlppKrmr** [comment]
Issue was resolved
