### ISSUE TITLE
Display all containers as list

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#41]
## User story
1. As a user
2. I want / need to see the containers saved in the database
3. So that I can gather information about them

## Acceptance criteria
- [x] Read the data provided by the database
- [x] Remove static data used previously
- [x] The list shows container name, container image
- [x] The user can click on the container name to navigate to the detail page

## Additional Notes
- The list is implemented with the list component

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Started.
Database connection is setup

**Comment by muhdfahadali** [comment]
The functionality has been implemented, but there are some issues with the pre-commits, which is why it has not been added to the release.

**Comment by freefreeP** [comment]
estimate 5 for setting up explorer testing with jest and writing test for this feature
