### ISSUE TITLE
Display container metadata in the container detail page

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#45]
## User story
1. As a user
2. I want / need to view the metadata of a container in its detail page
3. So that I can easily identify it

## Acceptance criteria
- [x] The container name is visible
- [x] The container image is visible
- [x] Data is loaded from the database

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Not picked up in sprint 6

**Comment by vringar** [comment]
Merged, documented

**Comment by PhlppKrmr** [comment]
Tests and Docuementation to be done

**Comment by vringar** [comment]
The feature as it is defined by the acceptance criteria is implemented, however it would be nice to fill the page entirely with real data and not use a mix of fake and real data.

**Comment by vringar** [comment]
#168 contains tests and removes all hardcoded information

**Comment by vringar** [comment]
#168 is merged
