### ISSUE TITLE
Make the container detail page accessible from the all containers view

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#48]
## User story
1. As a user
2. I want / need to access a container's detail page from the "All Containers" page
3. So that I can easily view detailed information

## Acceptance criteria
- [x] Each container listed in the "All Containers" view can be viewed in detail

## Additional Notes
[`<Link>`](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#link-component) is a React component that allows the UI to persist across navigation within the site.

This should be used in the ContainerTable and all other intra site navigations.

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by muhdfahadali** [comment]
changed <a> tags with <Link> tags
