### ISSUE TITLE
Display health state in list views

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#52]
## User story
1. As a user
2. I want / need to see the health state of rows in all list views
3. So that can quickly check the state and identify e.g. failing resources

## Acceptance criteria
- [x] Each row in a resource list contains a health indicator about that resource
- [x] The user can sort ASC/DESC on the health states

## Linked Issues
- **Related to**
   - #41 
   - #49 
- **Blocked by**
   - #32 
   - #31 

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by muhdfahadali** [comment]
Health state component is added to container list
Sorting ASC/DESC according to status is also implemented

**Comment by muhdfahadali** [comment]
Add cypress test case to test sort Asc/Desc.
