### ISSUE TITLE
Show parent pod of containers

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2023ss04-kubernetes-inventory-taker#54]
## User story
1. As a user
2. I want / need to see the parent pod of a container
3. So that it can figure out relations

## Acceptance criteria
- [ ] Parent pod is accessible from the contaner detail page

## Additional notes
- Pods and containers are referenced using external key in the database

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by smnws** [comment]
draft PR exists

**Comment by jandegen** [comment]
Not merged yet, update labels
