### ISSUE TITLE
Create sidebar navigation

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#60]
## User story
1. As a user
2. I want / need to be able to navigate to containers list, pods list and deployment lists
3. So that I can navigate to the resources and their detail pages as easily as possible

## Acceptance criteria
- [x] Sidebar navigation shows "All Containers" and linked with the list view of all containers
- [x] Sidebar navigation shows "All Pods"
- [x] Sidebar navigation shows "All Deployments"
- [x] Sidebar navigation shows "Dashboard" for navigating to the homepage

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by njochens** [comment]
Created draft PR and fixed some bugs

**Comment by jandegen** [comment]
Unit or e2e tests missing
