### ISSUE TITLE
Display pod metadata in the pod detail page

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#62]
## User story
1. As a user
2. I want / need to view the metadata of a pod in its detail page
3. So that I can easily identify it

## Acceptance criteria
- [x] The pod uid, name, namespace is visible
- [x] The health state of a pod is displayed
- [x] Child containers are listed with health indicators

## Additional notes
- Use the reusable component "detail page" created in #40 for the implementation

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Fahad started working on it

**Comment by muhdfahadali** [comment]
Pod details page created with pods details, pods and child container health indicators

**Comment by muhdfahadali** [comment]
tested with cypress  test case
