### ISSUE TITLE
Adjust database (scheme) to history approach

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#86]
## User story
1. As a developer
2. I want / need to adjust the current database (scheme) to a history design
3. So that I can persist historic changes

## Acceptance criteria
- [x] Database is able to store several versions of a resource
- [x] You can identify the current verision

## Linked Issues
- **Blocked by:**
- **Related to:**
- **Implements**

## Additional information
- none

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Waiting for merge to develop and documentation update in Confluence
