### ISSUE TITLE
Add prettier formatter for javascript to pre commit hooks

### ISSUE THREAD

**Issue by njochens** [amosproj/amos2023ss04-kubernetes-inventory-taker#90]
## User story
1. As a {}
2. I want / need {}
3. So that {}

## Acceptance criteria
- [ ]

## Linked Issues
- **Blocked by:**
- **Related to:**
- **Implements**

## Additional information
- none

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
Waiting for merge
