### ISSUE TITLE
Update wire draft

### ISSUE THREAD

**Issue by PhlppKrmr** [amosproj/amos2023ss04-kubernetes-inventory-taker#98]
## User story
1. As a developer
2. I want / need an updated version of the wire draft
3. So that I have an idea how the website is supposed to look like

## Acceptance criteria
- [x] Wire draft is updated

## Linked Issues
- **Blocked by:**
- **Related to: #76**
- **Implements:**

## Additional information
- We don't need a login/register page
- Health state should be core info

## Definition of done (DoD)
* Colours match with [color scheme](https://amos-p4.atlassian.net/l/cp/g5VzjL88)
* Implementation is unit tested
* Code documentation updated (jsdoc or godoc?)
* Changes to database documented at [Confluence- Database scheme](https://amos-p4.atlassian.net/l/cp/zY8cqaaP)
* Changes to architecture documented at [Confluence - Architecture](https://amos-p4.atlassian.net/l/cp/RT8RaER0)

## DoD general criteria
* Feature has been fully implemented
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Pull request to "develop" branch is merged & closed
* Bill of materials is updated with new dependencies

**Comment by jandegen** [comment]
- No login / user management requried
- Central component should be the health indicator
- Remove note buttons from from list views (Show that on the detail page)
- We just need 1 cluster
- Capacity columns for CPU, RAM, Storage & IP addresses
- Good visibility of health indicator on detail page (currently not clear where it is)
- Display children (of e.g. nodes like pods) within thew detail page
